export default {
  ROOM_SCREEN: "Rooms_screen",
  MESSAGE_SCREEN: "Message_screen",
  CONTROL_SCREEN: "Control_screen",
  USERS_CONTROL_SCREEN: "Users_control_screen",
  USER_DETAILS_SCREEN: "User_details_screen",
  CONTACTS_SCREEN: "Contacts_screen",
  ROOM_SETUP_SCREEN: "Room_setup_screen",
  USER_INFO_CARD_SCREEN: "user_info_card_screen",
  CREATE_CHANNEL_SCREEN: "create_channel_screen",
  CREATE_DIRECT_GROUP_SCREEN: "create_direct_group_screen",
  CREATE_CHAT_NAVIGATOR: "create_chat_navigator",
  TAB_NAVIGATOR: "tab_navigator",
  ADMIN_TAB_NAVIGATOR: "admin_tab_navigator",
  READ_BY_LIST: "Read_by_list",
};
